"""add pin and label to analysis history

Revision ID: 1aba6cb1abfc
Revises: 81bdc842d8f0
Create Date: 2026-09-07 22:25:13.290808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aba6cb1abfc'
down_revision: Union[str, Sequence[str], None] = '81bdc842d8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'analysis_history',
        sa.Column(
            'is_pinned',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false()
        )
    )

    op.add_column(
        'analysis_history',
        sa.Column(
            'label',
            sa.String(),
            nullable=True
        )
    )

    op.alter_column(
        'analysis_history',
        'is_pinned',
        server_default=None
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_history', 'label')
    op.drop_column('analysis_history', 'is_pinned')
    # ### end Alembic commands ###
